# example docker-compose configuration file for using mkodockx/docker-clamav:alpine
version: '3.7'

services:

  av:
    image: mkodockx/docker-clamav:alpine
    container_name: nextav
    restart: unless-stopped
    volumes:
      - /srv/opt/clam/conf:/etc/clamav/conf
      - /srv/opt/clam/store:/store

  app:
    image: nextcloud:production
    container_name: nextapp
    restart: unless-stopped
    env_file:
      - env/app.env
    volumes:
      - /srv/opt/nextcloud/html:/var/www/html
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    links:
      - av:av
      - db
      - redis
    depends_on: 
      - av
      - db
      - redis
    networks:
      outpost_network:
      default:
      
  db:
    image: mariadb
    container_name: nextdb
    restart: unless-stopped
    volumes:
      - /srv/opt/nextcloud/db:/var/lib/mysql
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    env_file:
      - env/db.env

  redis:
    image: redis:alpine
    container_name: nextredis
    restart: unless-stopped
  
networks:
  outpost_network:
    external: true
